# Generated by cpp4r: do not edit by hand

bvar_fn <- function(data_r, n_lags, constant, n_draws, seed) {
	.Call(`_cmw26_bvar_fn`, data_r, n_lags, constant, n_draws, seed)
}

comp_irf <- function(ME_r, MX_r, MY_r, nrep, kk) {
	.Call(`_cmw26_comp_irf`, ME_r, MX_r, MY_r, nrep, kk)
}

comp_irf_all <- function(ME_r, MX_r, MY_r, nrep) {
	.Call(`_cmw26_comp_irf_all`, ME_r, MX_r, MY_r, nrep)
}

var_irf <- function(B_r, Sigma_r, n_var, n_lags, n_hor) {
	.Call(`_cmw26_var_irf`, B_r, Sigma_r, n_var, n_lags, n_hor)
}

var_forecast <- function(data_r, n_lags, constant, B_r, fcst_date, fcst_length, hist_indic) {
	.Call(`_cmw26_var_forecast`, data_r, n_lags, constant, B_r, fcst_date, fcst_length, hist_indic)
}

var_forecast_errors <- function(data_r, n_lags, constant, B_r, fcst_date, fcst_length) {
	.Call(`_cmw26_var_forecast_errors`, data_r, n_lags, constant, B_r, fcst_date, fcst_length)
}

freq_var_fn <- function(theta_list, omega_1, omega_2, n_omega) {
	.Call(`_cmw26_freq_var_fn`, theta_list, omega_1, omega_2, n_omega)
}

freq_var_from_irf <- function(irf_r, n_y, n_e, n_hor, omega_1, omega_2, n_omega) {
	.Call(`_cmw26_freq_var_from_irf`, irf_r, n_y, n_e, n_hor, omega_1, omega_2, n_omega)
}

spectral_density <- function(theta_list, omega) {
	.Call(`_cmw26_spectral_density`, theta_list, omega)
}

bc_freq_var <- function(theta_list) {
	.Call(`_cmw26_bc_freq_var`, theta_list)
}

cnfctl_fn <- function(A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_r, Y_m_r, I_m_r, pi_z_r, y_z_r, i_z_r) {
	.Call(`_cmw26_cnfctl_fn`, A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_r, Y_m_r, I_m_r, pi_z_r, y_z_r, i_z_r)
}

cnfctl_pred_fn <- function(A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_r, Y_m_r, I_m_r, pi_x_r, y_x_r, i_x_r, hist_indic) {
	.Call(`_cmw26_cnfctl_pred_fn`, A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_r, Y_m_r, I_m_r, pi_x_r, y_x_r, i_x_r, hist_indic)
}

optpol_fn <- function(W_pi_r, W_y_r, W_i_r, Pi_m_r, Y_m_r, I_m_r, pi_z_r, y_z_r, i_z_r) {
	.Call(`_cmw26_optpol_fn`, W_pi_r, W_y_r, W_i_r, Pi_m_r, Y_m_r, I_m_r, pi_z_r, y_z_r, i_z_r)
}

vma_covariance <- function(wold_list) {
	.Call(`_cmw26_vma_covariance`, wold_list)
}

cov_to_corr <- function(cov_r) {
	.Call(`_cmw26_cov_to_corr`, cov_r)
}

cnfctl_batch <- function(A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_list, Y_m_list, I_m_list, pi_z_r, y_z_r, i_z_r) {
	.Call(`_cmw26_cnfctl_batch`, A_pi_r, A_y_r, A_i_r, wedge_r, Pi_m_list, Y_m_list, I_m_list, pi_z_r, y_z_r, i_z_r)
}

optpol_batch <- function(W_pi_r, W_y_r, W_i_r, Pi_m_list, Y_m_list, I_m_list, pi_z_r, y_z_r, i_z_r) {
	.Call(`_cmw26_optpol_batch`, W_pi_r, W_y_r, W_i_r, Pi_m_list, Y_m_list, I_m_list, pi_z_r, y_z_r, i_z_r)
}

winsorize_vec <- function(x_r, w) {
	.Call(`_cmw26_winsorize_vec`, x_r, w)
}

winsorize_mat <- function(x_r, w) {
	.Call(`_cmw26_winsorize_mat`, x_r, w)
}

ls_detrend <- function(Y_r, const_type) {
	.Call(`_cmw26_ls_detrend`, Y_r, const_type)
}

hamilton_filter <- function(Y_r, h, p) {
	.Call(`_cmw26_hamilton_filter`, Y_r, h, p)
}

kernel_density <- function(x_r, xi_r, h, ktype) {
	.Call(`_cmw26_kernel_density`, x_r, xi_r, h, ktype)
}

quantile_vec <- function(x_r, probs_r) {
	.Call(`_cmw26_quantile_vec`, x_r, probs_r)
}

quantile_mat <- function(x_r, probs_r) {
	.Call(`_cmw26_quantile_mat`, x_r, probs_r)
}

sample_models <- function(n_draws, model_probs_r) {
	.Call(`_cmw26_sample_models`, n_draws, model_probs_r)
}

stack_matrices <- function(mat_list) {
	.Call(`_cmw26_stack_matrices`, mat_list)
}
