// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// main.cpp
writable::doubles_matrix<> cck94_stats(list args, int n_k, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_stats(SEXP args, SEXP n_k, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_stats(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::doubles_matrix<> cck94_params(list args);
extern "C" SEXP _cck94_cck94_params(SEXP args) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_params(cpp4r::as_cpp<cpp4r::decay_t<list>>(args)));
  END_CPP4R
}
// main.cpp
writable::doubles_matrix<> cck94_diag(list args);
extern "C" SEXP _cck94_cck94_diag(SEXP args) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_diag(cpp4r::as_cpp<cpp4r::decay_t<list>>(args)));
  END_CPP4R
}
// main.cpp
writable::doubles_matrix<> cck94_stats_2nd(list args, int n_k, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_stats_2nd(SEXP args, SEXP n_k, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_stats_2nd(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::list cck94_solve_ti(list args, int n_k, int n_z, int n_g, int max_iter, double tol, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_solve_ti(SEXP args, SEXP n_k, SEXP n_z, SEXP n_g, SEXP max_iter, SEXP tol, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_solve_ti(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_z), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_g), cpp4r::as_cpp<cpp4r::decay_t<int>>(max_iter), cpp4r::as_cpp<cpp4r::decay_t<double>>(tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::list cck94_solve_egm(list args, int n_k, int n_z, int n_g, int max_iter, double tol, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_solve_egm(SEXP args, SEXP n_k, SEXP n_z, SEXP n_g, SEXP max_iter, SEXP tol, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_solve_egm(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_z), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_g), cpp4r::as_cpp<cpp4r::decay_t<int>>(max_iter), cpp4r::as_cpp<cpp4r::decay_t<double>>(tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::list cck94_solve_ecm(list args, int n_k, int n_z, int n_g, int max_iter, double tol, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_solve_ecm(SEXP args, SEXP n_k, SEXP n_z, SEXP n_g, SEXP max_iter, SEXP tol, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_solve_ecm(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_z), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_g), cpp4r::as_cpp<cpp4r::decay_t<int>>(max_iter), cpp4r::as_cpp<cpp4r::decay_t<double>>(tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::list cck94_solve_proj(list args, int n_k, int n_z, int n_g, int poly_degree, int max_iter, double tol, int T_total, int T_burn, int seed);
extern "C" SEXP _cck94_cck94_solve_proj(SEXP args, SEXP n_k, SEXP n_z, SEXP n_g, SEXP poly_degree, SEXP max_iter, SEXP tol, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cck94_solve_proj(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_z), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_g), cpp4r::as_cpp<cpp4r::decay_t<int>>(poly_degree), cpp4r::as_cpp<cpp4r::decay_t<int>>(max_iter), cpp4r::as_cpp<cpp4r::decay_t<double>>(tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cck94_cck94_diag",       (DL_FUNC) &_cck94_cck94_diag,        1},
    {"_cck94_cck94_params",     (DL_FUNC) &_cck94_cck94_params,      1},
    {"_cck94_cck94_solve_ecm",  (DL_FUNC) &_cck94_cck94_solve_ecm,   9},
    {"_cck94_cck94_solve_egm",  (DL_FUNC) &_cck94_cck94_solve_egm,   9},
    {"_cck94_cck94_solve_proj", (DL_FUNC) &_cck94_cck94_solve_proj, 10},
    {"_cck94_cck94_solve_ti",   (DL_FUNC) &_cck94_cck94_solve_ti,    9},
    {"_cck94_cck94_stats",      (DL_FUNC) &_cck94_cck94_stats,       5},
    {"_cck94_cck94_stats_2nd",  (DL_FUNC) &_cck94_cck94_stats_2nd,   5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cck94(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
