// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// 01_bvar.h
list bvar_fn(const doubles_matrix<>& data_r, int n_lags, int constant, int n_draws, int seed);
extern "C" SEXP _cmw26_bvar_fn(SEXP data_r, SEXP n_lags, SEXP constant, SEXP n_draws, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(bvar_fn(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(data_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_lags), cpp4r::as_cpp<cpp4r::decay_t<int>>(constant), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_draws), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// 02_comp_irf.h
list comp_irf(const doubles_matrix<>& ME_r, const doubles_matrix<>& MX_r, const doubles_matrix<>& MY_r, int nrep, int kk);
extern "C" SEXP _cmw26_comp_irf(SEXP ME_r, SEXP MX_r, SEXP MY_r, SEXP nrep, SEXP kk) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(comp_irf(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(ME_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(MX_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(MY_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(nrep), cpp4r::as_cpp<cpp4r::decay_t<int>>(kk)));
  END_CPP4R
}
// 02_comp_irf.h
list comp_irf_all(const doubles_matrix<>& ME_r, const doubles_matrix<>& MX_r, const doubles_matrix<>& MY_r, int nrep);
extern "C" SEXP _cmw26_comp_irf_all(SEXP ME_r, SEXP MX_r, SEXP MY_r, SEXP nrep) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(comp_irf_all(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(ME_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(MX_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(MY_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(nrep)));
  END_CPP4R
}
// 02_comp_irf.h
list var_irf(const doubles_matrix<>& B_r, const doubles_matrix<>& Sigma_r, int n_var, int n_lags, int n_hor);
extern "C" SEXP _cmw26_var_irf(SEXP B_r, SEXP Sigma_r, SEXP n_var, SEXP n_lags, SEXP n_hor) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(var_irf(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(B_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Sigma_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_var), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_lags), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_hor)));
  END_CPP4R
}
// 03_forecast.h
doubles_matrix<> var_forecast(const doubles_matrix<>& data_r, int n_lags, int constant, const doubles_matrix<>& B_r, int fcst_date, int fcst_length, int hist_indic);
extern "C" SEXP _cmw26_var_forecast(SEXP data_r, SEXP n_lags, SEXP constant, SEXP B_r, SEXP fcst_date, SEXP fcst_length, SEXP hist_indic) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(var_forecast(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(data_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_lags), cpp4r::as_cpp<cpp4r::decay_t<int>>(constant), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(B_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(fcst_date), cpp4r::as_cpp<cpp4r::decay_t<int>>(fcst_length), cpp4r::as_cpp<cpp4r::decay_t<int>>(hist_indic)));
  END_CPP4R
}
// 03_forecast.h
list var_forecast_errors(const doubles_matrix<>& data_r, int n_lags, int constant, const doubles_matrix<>& B_r, int fcst_date, int fcst_length);
extern "C" SEXP _cmw26_var_forecast_errors(SEXP data_r, SEXP n_lags, SEXP constant, SEXP B_r, SEXP fcst_date, SEXP fcst_length) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(var_forecast_errors(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(data_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_lags), cpp4r::as_cpp<cpp4r::decay_t<int>>(constant), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(B_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(fcst_date), cpp4r::as_cpp<cpp4r::decay_t<int>>(fcst_length)));
  END_CPP4R
}
// 04_freq_var.h
doubles_matrix<> freq_var_fn(const list& theta_list, double omega_1, double omega_2, int n_omega);
extern "C" SEXP _cmw26_freq_var_fn(SEXP theta_list, SEXP omega_1, SEXP omega_2, SEXP n_omega) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(freq_var_fn(cpp4r::as_cpp<cpp4r::decay_t<const list&>>(theta_list), cpp4r::as_cpp<cpp4r::decay_t<double>>(omega_1), cpp4r::as_cpp<cpp4r::decay_t<double>>(omega_2), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_omega)));
  END_CPP4R
}
// 04_freq_var.h
doubles_matrix<> freq_var_from_irf(const doubles_matrix<>& irf_r, int n_y, int n_e, int n_hor, double omega_1, double omega_2, int n_omega);
extern "C" SEXP _cmw26_freq_var_from_irf(SEXP irf_r, SEXP n_y, SEXP n_e, SEXP n_hor, SEXP omega_1, SEXP omega_2, SEXP n_omega) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(freq_var_from_irf(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(irf_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_y), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_e), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_hor), cpp4r::as_cpp<cpp4r::decay_t<double>>(omega_1), cpp4r::as_cpp<cpp4r::decay_t<double>>(omega_2), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_omega)));
  END_CPP4R
}
// 04_freq_var.h
doubles_matrix<> spectral_density(const list& theta_list, double omega);
extern "C" SEXP _cmw26_spectral_density(SEXP theta_list, SEXP omega) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(spectral_density(cpp4r::as_cpp<cpp4r::decay_t<const list&>>(theta_list), cpp4r::as_cpp<cpp4r::decay_t<double>>(omega)));
  END_CPP4R
}
// 04_freq_var.h
doubles_matrix<> bc_freq_var(const list& theta_list);
extern "C" SEXP _cmw26_bc_freq_var(SEXP theta_list) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(bc_freq_var(cpp4r::as_cpp<cpp4r::decay_t<const list&>>(theta_list)));
  END_CPP4R
}
// 05_cnfctl.h
list cnfctl_fn(const doubles_matrix<>& A_pi_r, const doubles_matrix<>& A_y_r, const doubles_matrix<>& A_i_r, const doubles& wedge_r, const doubles_matrix<>& Pi_m_r, const doubles_matrix<>& Y_m_r, const doubles_matrix<>& I_m_r, const doubles& pi_z_r, const doubles& y_z_r, const doubles& i_z_r);
extern "C" SEXP _cmw26_cnfctl_fn(SEXP A_pi_r, SEXP A_y_r, SEXP A_i_r, SEXP wedge_r, SEXP Pi_m_r, SEXP Y_m_r, SEXP I_m_r, SEXP pi_z_r, SEXP y_z_r, SEXP i_z_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cnfctl_fn(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_pi_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_i_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(wedge_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Pi_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Y_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(I_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(pi_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(y_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(i_z_r)));
  END_CPP4R
}
// 05_cnfctl.h
list cnfctl_pred_fn(const doubles_matrix<>& A_pi_r, const doubles_matrix<>& A_y_r, const doubles_matrix<>& A_i_r, const doubles& wedge_r, const doubles_matrix<>& Pi_m_r, const doubles_matrix<>& Y_m_r, const doubles_matrix<>& I_m_r, const doubles& pi_x_r, const doubles& y_x_r, const doubles& i_x_r, int hist_indic);
extern "C" SEXP _cmw26_cnfctl_pred_fn(SEXP A_pi_r, SEXP A_y_r, SEXP A_i_r, SEXP wedge_r, SEXP Pi_m_r, SEXP Y_m_r, SEXP I_m_r, SEXP pi_x_r, SEXP y_x_r, SEXP i_x_r, SEXP hist_indic) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cnfctl_pred_fn(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_pi_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_i_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(wedge_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Pi_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Y_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(I_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(pi_x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(y_x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(i_x_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(hist_indic)));
  END_CPP4R
}
// 05_cnfctl.h
list optpol_fn(const doubles_matrix<>& W_pi_r, const doubles_matrix<>& W_y_r, const doubles_matrix<>& W_i_r, const doubles_matrix<>& Pi_m_r, const doubles_matrix<>& Y_m_r, const doubles_matrix<>& I_m_r, const doubles& pi_z_r, const doubles& y_z_r, const doubles& i_z_r);
extern "C" SEXP _cmw26_optpol_fn(SEXP W_pi_r, SEXP W_y_r, SEXP W_i_r, SEXP Pi_m_r, SEXP Y_m_r, SEXP I_m_r, SEXP pi_z_r, SEXP y_z_r, SEXP i_z_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(optpol_fn(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_pi_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_i_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Pi_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Y_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(I_m_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(pi_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(y_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(i_z_r)));
  END_CPP4R
}
// 05_cnfctl.h
doubles_matrix<> vma_covariance(const list& wold_list);
extern "C" SEXP _cmw26_vma_covariance(SEXP wold_list) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(vma_covariance(cpp4r::as_cpp<cpp4r::decay_t<const list&>>(wold_list)));
  END_CPP4R
}
// 05_cnfctl.h
doubles_matrix<> cov_to_corr(const doubles_matrix<>& cov_r);
extern "C" SEXP _cmw26_cov_to_corr(SEXP cov_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cov_to_corr(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(cov_r)));
  END_CPP4R
}
// 05_cnfctl.h
list cnfctl_batch(const doubles_matrix<>& A_pi_r, const doubles_matrix<>& A_y_r, const doubles_matrix<>& A_i_r, const doubles& wedge_r, const list& Pi_m_list, const list& Y_m_list, const list& I_m_list, const doubles& pi_z_r, const doubles& y_z_r, const doubles& i_z_r);
extern "C" SEXP _cmw26_cnfctl_batch(SEXP A_pi_r, SEXP A_y_r, SEXP A_i_r, SEXP wedge_r, SEXP Pi_m_list, SEXP Y_m_list, SEXP I_m_list, SEXP pi_z_r, SEXP y_z_r, SEXP i_z_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cnfctl_batch(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_pi_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(A_i_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(wedge_r), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(Pi_m_list), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(Y_m_list), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(I_m_list), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(pi_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(y_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(i_z_r)));
  END_CPP4R
}
// 05_cnfctl.h
list optpol_batch(const doubles_matrix<>& W_pi_r, const doubles_matrix<>& W_y_r, const doubles_matrix<>& W_i_r, const list& Pi_m_list, const list& Y_m_list, const list& I_m_list, const doubles& pi_z_r, const doubles& y_z_r, const doubles& i_z_r);
extern "C" SEXP _cmw26_optpol_batch(SEXP W_pi_r, SEXP W_y_r, SEXP W_i_r, SEXP Pi_m_list, SEXP Y_m_list, SEXP I_m_list, SEXP pi_z_r, SEXP y_z_r, SEXP i_z_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(optpol_batch(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_pi_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(W_i_r), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(Pi_m_list), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(Y_m_list), cpp4r::as_cpp<cpp4r::decay_t<const list&>>(I_m_list), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(pi_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(y_z_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(i_z_r)));
  END_CPP4R
}
// 06_utils.h
doubles winsorize_vec(const doubles& x_r, double w);
extern "C" SEXP _cmw26_winsorize_vec(SEXP x_r, SEXP w) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(winsorize_vec(cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<double>>(w)));
  END_CPP4R
}
// 06_utils.h
doubles_matrix<> winsorize_mat(const doubles_matrix<>& x_r, double w);
extern "C" SEXP _cmw26_winsorize_mat(SEXP x_r, SEXP w) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(winsorize_mat(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<double>>(w)));
  END_CPP4R
}
// 06_utils.h
list ls_detrend(const doubles_matrix<>& Y_r, int const_type);
extern "C" SEXP _cmw26_ls_detrend(SEXP Y_r, SEXP const_type) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(ls_detrend(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(Y_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(const_type)));
  END_CPP4R
}
// 06_utils.h
doubles hamilton_filter(const doubles& Y_r, int h, int p);
extern "C" SEXP _cmw26_hamilton_filter(SEXP Y_r, SEXP h, SEXP p) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(hamilton_filter(cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(Y_r), cpp4r::as_cpp<cpp4r::decay_t<int>>(h), cpp4r::as_cpp<cpp4r::decay_t<int>>(p)));
  END_CPP4R
}
// 06_utils.h
doubles kernel_density(const doubles& x_r, const doubles& xi_r, double h, int ktype);
extern "C" SEXP _cmw26_kernel_density(SEXP x_r, SEXP xi_r, SEXP h, SEXP ktype) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(kernel_density(cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(xi_r), cpp4r::as_cpp<cpp4r::decay_t<double>>(h), cpp4r::as_cpp<cpp4r::decay_t<int>>(ktype)));
  END_CPP4R
}
// 06_utils.h
doubles quantile_vec(const doubles& x_r, const doubles& probs_r);
extern "C" SEXP _cmw26_quantile_vec(SEXP x_r, SEXP probs_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(quantile_vec(cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(probs_r)));
  END_CPP4R
}
// 06_utils.h
doubles_matrix<> quantile_mat(const doubles_matrix<>& x_r, const doubles& probs_r);
extern "C" SEXP _cmw26_quantile_mat(SEXP x_r, SEXP probs_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(quantile_mat(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<>&>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(probs_r)));
  END_CPP4R
}
// 06_utils.h
integers sample_models(int n_draws, const doubles& model_probs_r);
extern "C" SEXP _cmw26_sample_models(SEXP n_draws, SEXP model_probs_r) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sample_models(cpp4r::as_cpp<cpp4r::decay_t<int>>(n_draws), cpp4r::as_cpp<cpp4r::decay_t<const doubles&>>(model_probs_r)));
  END_CPP4R
}
// 06_utils.h
doubles_matrix<> stack_matrices(const list& mat_list);
extern "C" SEXP _cmw26_stack_matrices(SEXP mat_list) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(stack_matrices(cpp4r::as_cpp<cpp4r::decay_t<const list&>>(mat_list)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cmw26_bc_freq_var",         (DL_FUNC) &_cmw26_bc_freq_var,          1},
    {"_cmw26_bvar_fn",             (DL_FUNC) &_cmw26_bvar_fn,              5},
    {"_cmw26_cnfctl_batch",        (DL_FUNC) &_cmw26_cnfctl_batch,        10},
    {"_cmw26_cnfctl_fn",           (DL_FUNC) &_cmw26_cnfctl_fn,           10},
    {"_cmw26_cnfctl_pred_fn",      (DL_FUNC) &_cmw26_cnfctl_pred_fn,      11},
    {"_cmw26_comp_irf",            (DL_FUNC) &_cmw26_comp_irf,             5},
    {"_cmw26_comp_irf_all",        (DL_FUNC) &_cmw26_comp_irf_all,         4},
    {"_cmw26_cov_to_corr",         (DL_FUNC) &_cmw26_cov_to_corr,          1},
    {"_cmw26_freq_var_fn",         (DL_FUNC) &_cmw26_freq_var_fn,          4},
    {"_cmw26_freq_var_from_irf",   (DL_FUNC) &_cmw26_freq_var_from_irf,    7},
    {"_cmw26_hamilton_filter",     (DL_FUNC) &_cmw26_hamilton_filter,      3},
    {"_cmw26_kernel_density",      (DL_FUNC) &_cmw26_kernel_density,       4},
    {"_cmw26_ls_detrend",          (DL_FUNC) &_cmw26_ls_detrend,           2},
    {"_cmw26_optpol_batch",        (DL_FUNC) &_cmw26_optpol_batch,         9},
    {"_cmw26_optpol_fn",           (DL_FUNC) &_cmw26_optpol_fn,            9},
    {"_cmw26_quantile_mat",        (DL_FUNC) &_cmw26_quantile_mat,         2},
    {"_cmw26_quantile_vec",        (DL_FUNC) &_cmw26_quantile_vec,         2},
    {"_cmw26_sample_models",       (DL_FUNC) &_cmw26_sample_models,        2},
    {"_cmw26_spectral_density",    (DL_FUNC) &_cmw26_spectral_density,     2},
    {"_cmw26_stack_matrices",      (DL_FUNC) &_cmw26_stack_matrices,       1},
    {"_cmw26_var_forecast",        (DL_FUNC) &_cmw26_var_forecast,         7},
    {"_cmw26_var_forecast_errors", (DL_FUNC) &_cmw26_var_forecast_errors,  6},
    {"_cmw26_var_irf",             (DL_FUNC) &_cmw26_var_irf,              5},
    {"_cmw26_vma_covariance",      (DL_FUNC) &_cmw26_vma_covariance,       1},
    {"_cmw26_winsorize_mat",       (DL_FUNC) &_cmw26_winsorize_mat,        2},
    {"_cmw26_winsorize_vec",       (DL_FUNC) &_cmw26_winsorize_vec,        2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cmw26(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
