// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// main.cpp
writable::doubles_matrix<> bw05_stats(list args, int n_k, int T_total, int T_burn, int seed);
extern "C" SEXP _bw05_bw05_stats(SEXP args, SEXP n_k, SEXP T_total, SEXP T_burn, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(bw05_stats(cpp4r::as_cpp<cpp4r::decay_t<list>>(args), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_k), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_total), cpp4r::as_cpp<cpp4r::decay_t<int>>(T_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// main.cpp
writable::doubles_matrix<> bw05_params(list args);
extern "C" SEXP _bw05_bw05_params(SEXP args) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(bw05_params(cpp4r::as_cpp<cpp4r::decay_t<list>>(args)));
  END_CPP4R
}
// main.cpp
writable::doubles_matrix<> bw05_diag(list args);
extern "C" SEXP _bw05_bw05_diag(SEXP args) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(bw05_diag(cpp4r::as_cpp<cpp4r::decay_t<list>>(args)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_bw05_bw05_diag",   (DL_FUNC) &_bw05_bw05_diag,   1},
    {"_bw05_bw05_params", (DL_FUNC) &_bw05_bw05_params, 1},
    {"_bw05_bw05_stats",  (DL_FUNC) &_bw05_bw05_stats,  5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_bw05(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
