# Generated by cpp4r: do not edit by hand

#' @title BW Table 5: 1st-order Monte Carlo statistics
#' @description Simulates log-linearized Ramsey policy rules using BW's
#'   LQ approach and returns the same statistics as Table 5 of Benigno &
#'   Woodford (2005).
#' @export
bw05_stats <- function(args, n_k, T_total, T_burn, seed) {
	.Call(`_bw05_bw05_stats`, args, n_k, T_total, T_burn, seed)
}

#' @title NSSS and LQ diagnostics
#' @description Returns steady-state shares, BW utility coefficients, and
#'   LQ loss function coefficients for diagnostic purposes.
#' @export
bw05_params <- function(args) {
	.Call(`_bw05_bw05_params`, args)
}

#' @title Full decision rule diagnostics
#' @description Returns gx, hx, and all BW tax formula coefficients.
#' @export
bw05_diag <- function(args) {
	.Call(`_bw05_bw05_diag`, args)
}
